# Generated by Django 6.0.6 on 2026-07-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_parentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentuser',
            name='token',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
